[package]
authors = ["Magnus Hoff <maghoff@gmail.com>"]
build = "migrate.rs"
name = "fishsticks"
version = "0.1.0"

[build-dependencies]

[build-dependencies.diesel]
default-features = false
features = ["sqlite"]
version = "^0.9.0"

[dependencies]
bodyparser = "0.4.1"
getopts = "^0.2.14"
iron = "^0.4.0"
itertools = "0.5.6"
num = "0.1.36"
quick-error = "^1.1.0"
rand = "0.3.14"
router = "^0.4.0"
serde = "^0.8.17"
serde_derive = "^0.8.17"
serde_json = "^0.8.3"
time = "0.1.35"
urlencoded = "0.4.1"

[dependencies.diesel]
default-features = false
features = ["sqlite"]
version = "^0.9.0"

[dependencies.diesel_codegen]
default-features = false
features = ["sqlite"]
version = "^0.9.0"

[dependencies.handlebars]
features = ["serde_type"]
version = "^0.23.0"

[dependencies.handlebars-iron]
features = ["serde_type"]
version = "^0.19.2"

[dependencies.hyper]
version = "^0.9.12"
default_features = false
features = ["security-framework"]

[dependencies.sharebill]
path = "libs/sharebill"

[dependencies.uuid]
features = ["use_std", "v4"]
version = "^0.2"
