[package]
authors = ["Magnus Hoff <maghoff@gmail.com>"]
build = "migrate.rs"
name = "fishsticks"
version = "0.1.0"

[build-dependencies]

[build-dependencies.diesel]
default-features = false
features = ["sqlite"]
version = "^0.8.1"

[dependencies]
bodyparser = "0.4.1"
getopts = "^0.2.14"
iron = "^0.4.0"
quick-error = "^1.1.0"
router = "^0.4.0"
serde = "^0.8.17"
serde_derive = "^0.8.17"
serde_json = "^0.8.3"

[dependencies.diesel]
default-features = false
features = ["sqlite"]
version = "^0.8.1"

[dependencies.diesel_codegen]
default-features = false
features = ["sqlite"]
version = "^0.8.1"

[dependencies.handlebars]
features = ["serde_type"]
version = "^0.22.0"

[dependencies.handlebars-iron]
features = ["serde_type"]
version = "^0.19.2"
