[package]
authors = ["Magnus Hoff <maghoff@gmail.com>"]
build = "migrate.rs"
name = "fishsticks"
version = "0.1.0"

[build-dependencies.diesel]
version = "^0.8.1"
default-features = false
features = ["sqlite"]

[dependencies]
getopts = "^0.2.14"
handlebars = { version = "^0.22.0", features = ["serde_type"] }
handlebars-iron = { version = "^0.19.2", features = ["serde_type"] }
iron = "^0.4.0"
quick-error = "^1.1.0"
router = "^0.4.0"
serde = "^0.8.17"
serde_derive = "^0.8.17"
serde_json = "^0.8.3"

[dependencies.diesel]
version = "^0.8.1"
default-features = false
features = ["sqlite"]

[dependencies.diesel_codegen]
version = "^0.8.1"
default-features = false
features = ["sqlite"]
